default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: eworks_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: eworks_test


production:
  <<: *default
  database: eworks_production
  username: eworks
  password: <%= ENV["EWORKS_DATABASE_PASSWORD"] %>
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
